import { createFileRoute, Link } from "@tanstack/react-router";
import { ClipboardList, Clock, MapPin } from "lucide-react";
import { useEffect, useState } from "react";
import { BottomNav } from "@/shared/layout/BottomNav";
import { useAuth, useCustomerGuard } from "@/features/auth/auth.context";
import { supabase } from "@/integrations/supabase/client";
import { formatILS } from "@/features/offers/offers.service";

export const Route = createFileRoute("/orders")({ head: () => ({ meta: [{ title: "طلباتي | Selecto" }] }), component: OrdersPage });
type Tx = { id: string; sale_amount: number; customer_total_price: number | null; status: string | null; fulfillment_type: string | null; delivery_address: string | null; quantity: number | null; customer_note: string | null; cancellation_reason: string | null; created_at: string; offers?: { name: string; image: string | null; pickup_time?: string | null } | null; restaurants?: { name: string; city?: string | null } | null; };
const statusLabels: Record<string, string> = { confirmed: "مؤكد", ready_for_pickup: "جاهز للاستلام", completed: "مكتمل", cancelled: "ملغي" };
function OrdersPage() {
  const { user } = useAuth();
  const [transactions, setTransactions] = useState<Tx[]>([]);
  const [loading, setLoading] = useState(true);
  useCustomerGuard();
  useEffect(() => { if (!user) { setLoading(false); return; } supabase.from("transactions").select("id, sale_amount, customer_total_price, status, fulfillment_type, delivery_address, quantity, customer_note, cancellation_reason, created_at, offers(name, image, pickup_time), restaurants(name, city)").eq("customer_id", user.id).order("created_at", { ascending: false }).then(({ data }) => setTransactions((data as Tx[]) ?? [])).finally(() => setLoading(false)); }, [user]);
  return <div className="phone-frame min-h-screen bg-background pb-20 text-foreground"><header className="border-b border-border bg-card px-5 py-5 text-right" dir="rtl"><h1 className="font-display text-2xl font-black">طلباتي</h1><p className="mt-1 text-xs font-bold text-muted-foreground">تابع حالة الحجز ووقت الاستلام.</p></header><main className="space-y-4 px-5 py-5">{!user ? <EmptyState title="سجل دخولك لعرض الطلبات" cta="تسجيل الدخول" to="/auth" /> : loading ? <StateCard title="جاري تحميل طلباتك..." /> : transactions.length === 0 ? <EmptyState title="لا توجد طلبات بعد" cta="تصفح العروض" to="/offers" /> : transactions.map((tx) => <OrderCard key={tx.id} tx={tx} />)}</main><BottomNav /></div>;
}
function OrderCard({ tx }: { tx: Tx }) { const status = tx.status || "confirmed"; const total = Number(tx.customer_total_price ?? tx.sale_amount); return <article className="rounded-2xl border border-border bg-card p-4 shadow-sm" dir="rtl"><div className="flex gap-3">{tx.offers?.image ? <img src={tx.offers.image} alt="" className="size-16 shrink-0 rounded-xl object-cover" /> : <div className="grid size-16 shrink-0 place-items-center rounded-xl bg-secondary text-primary"><ClipboardList className="size-6" /></div>}<div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><h2 className="truncate text-sm font-black">{tx.offers?.name ?? "طلب Selecto"} <span className="text-primary opacity-80">(x{tx.quantity || 1})</span></h2><p className="mt-1 flex items-center gap-1 text-xs font-bold text-muted-foreground"><MapPin className="size-3" />{tx.restaurants?.name ?? "مطعم محلي"}</p></div><span className={`shrink-0 rounded-full px-3 py-1 text-[10px] font-black ${status === 'cancelled' ? 'bg-destructive/10 text-destructive' : 'bg-primary/10 text-primary'}`}>{statusLabels[status] ?? status}</span></div>{tx.customer_note && <p className="mt-2 text-xs font-medium text-warning opacity-90">📝 ملاحظاتك: {tx.customer_note}</p>}{status === 'cancelled' && tx.cancellation_reason && <p className="mt-1 text-xs font-bold text-destructive">سبب الإلغاء: {tx.cancellation_reason}</p>}<div className="mt-4 grid gap-2 text-xs font-bold text-muted-foreground"><div className="flex items-center justify-between"><span className="flex items-center gap-1"><Clock className="size-3" />{tx.fulfillment_type === 'delivery' ? 'طريقة الاستلام' : 'وقت الاستلام'}</span><span className="text-primary">{tx.fulfillment_type === 'delivery' ? 'توصيل' : (tx.offers?.pickup_time || "يحدده المطعم")}</span></div>{tx.fulfillment_type === 'delivery' && <div className="text-[11px] leading-relaxed opacity-80">📍 {tx.delivery_address}</div>}<div className="flex items-center justify-between border-t border-border pt-3 text-sm font-black"><span className="text-foreground">الإجمالي {tx.fulfillment_type === 'delivery' ? '(غير شامل التوصيل)' : ''}</span><span className="text-primary">{formatILS(total)}</span></div></div></div></div></article>; }
function EmptyState({ title, cta, to }: { title: string; cta: string; to: string }) { return <div className="grid place-items-center rounded-2xl border border-dashed border-border bg-card px-6 py-14 text-center"><div><div className="mx-auto grid size-16 place-items-center rounded-full bg-secondary text-primary"><ClipboardList className="size-7" /></div><h2 className="mt-4 font-display text-lg font-black">{title}</h2><Link to={to} className="mt-5 inline-flex rounded-xl bg-primary px-5 py-3 text-sm font-black text-primary-foreground">{cta}</Link></div></div>; }
function StateCard({ title }: { title: string }) { return <div className="rounded-2xl border border-border bg-card px-5 py-10 text-center text-sm font-black text-muted-foreground">{title}</div>; }
