/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as OfferIdRouteImport } from './routes/offer.$id'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardOffersIndexRouteImport } from './routes/dashboard.offers.index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard.admin.index'
import { Route as DashboardOffersNewRouteImport } from './routes/dashboard.offers.new'
import { Route as DashboardAdminRestaurantsRouteImport } from './routes/dashboard.admin.restaurants'
import { Route as DashboardAdminOffersRouteImport } from './routes/dashboard.admin.offers'
import { Route as DashboardOffersEditIdRouteImport } from './routes/dashboard.offers.edit.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const OfferIdRoute = OfferIdRouteImport.update({
  id: '/offer/$id',
  path: '/offer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOffersIndexRoute = DashboardOffersIndexRouteImport.update({
  id: '/offers/',
  path: '/offers/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOffersNewRoute = DashboardOffersNewRouteImport.update({
  id: '/offers/new',
  path: '/offers/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRestaurantsRoute =
  DashboardAdminRestaurantsRouteImport.update({
    id: '/admin/restaurants',
    path: '/admin/restaurants',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminOffersRoute = DashboardAdminOffersRouteImport.update({
  id: '/admin/offers',
  path: '/admin/offers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOffersEditIdRoute = DashboardOffersEditIdRouteImport.update({
  id: '/offers/edit/$id',
  path: '/offers/edit/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/delete-account': typeof DeleteAccountRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/restaurants': typeof RestaurantsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/offer/$id': typeof OfferIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/offers': typeof DashboardAdminOffersRoute
  '/dashboard/admin/restaurants': typeof DashboardAdminRestaurantsRoute
  '/dashboard/offers/new': typeof DashboardOffersNewRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/offers/': typeof DashboardOffersIndexRoute
  '/dashboard/offers/edit/$id': typeof DashboardOffersEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/delete-account': typeof DeleteAccountRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/restaurants': typeof RestaurantsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/offer/$id': typeof OfferIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/offers': typeof DashboardAdminOffersRoute
  '/dashboard/admin/restaurants': typeof DashboardAdminRestaurantsRoute
  '/dashboard/offers/new': typeof DashboardOffersNewRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/offers': typeof DashboardOffersIndexRoute
  '/dashboard/offers/edit/$id': typeof DashboardOffersEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/delete-account': typeof DeleteAccountRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/restaurants': typeof RestaurantsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/offer/$id': typeof OfferIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/offers': typeof DashboardAdminOffersRoute
  '/dashboard/admin/restaurants': typeof DashboardAdminRestaurantsRoute
  '/dashboard/offers/new': typeof DashboardOffersNewRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/offers/': typeof DashboardOffersIndexRoute
  '/dashboard/offers/edit/$id': typeof DashboardOffersEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/dashboard'
    | '/delete-account'
    | '/explore'
    | '/favorites'
    | '/offers'
    | '/orders'
    | '/portal'
    | '/privacy'
    | '/profile'
    | '/restaurants'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/dashboard/analytics'
    | '/dashboard/orders'
    | '/dashboard/settings'
    | '/offer/$id'
    | '/dashboard/'
    | '/dashboard/admin/offers'
    | '/dashboard/admin/restaurants'
    | '/dashboard/offers/new'
    | '/dashboard/admin/'
    | '/dashboard/offers/'
    | '/dashboard/offers/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/delete-account'
    | '/explore'
    | '/favorites'
    | '/offers'
    | '/orders'
    | '/portal'
    | '/privacy'
    | '/profile'
    | '/restaurants'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/dashboard/analytics'
    | '/dashboard/orders'
    | '/dashboard/settings'
    | '/offer/$id'
    | '/dashboard'
    | '/dashboard/admin/offers'
    | '/dashboard/admin/restaurants'
    | '/dashboard/offers/new'
    | '/dashboard/admin'
    | '/dashboard/offers'
    | '/dashboard/offers/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/dashboard'
    | '/delete-account'
    | '/explore'
    | '/favorites'
    | '/offers'
    | '/orders'
    | '/portal'
    | '/privacy'
    | '/profile'
    | '/restaurants'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/dashboard/analytics'
    | '/dashboard/orders'
    | '/dashboard/settings'
    | '/offer/$id'
    | '/dashboard/'
    | '/dashboard/admin/offers'
    | '/dashboard/admin/restaurants'
    | '/dashboard/offers/new'
    | '/dashboard/admin/'
    | '/dashboard/offers/'
    | '/dashboard/offers/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DeleteAccountRoute: typeof DeleteAccountRoute
  ExploreRoute: typeof ExploreRoute
  FavoritesRoute: typeof FavoritesRoute
  OffersRoute: typeof OffersRoute
  OrdersRoute: typeof OrdersRoute
  PortalRoute: typeof PortalRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RestaurantsRoute: typeof RestaurantsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  OfferIdRoute: typeof OfferIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/offer/$id': {
      id: '/offer/$id'
      path: '/offer/$id'
      fullPath: '/offer/$id'
      preLoaderRoute: typeof OfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/offers/': {
      id: '/dashboard/offers/'
      path: '/offers'
      fullPath: '/dashboard/offers/'
      preLoaderRoute: typeof DashboardOffersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/offers/new': {
      id: '/dashboard/offers/new'
      path: '/offers/new'
      fullPath: '/dashboard/offers/new'
      preLoaderRoute: typeof DashboardOffersNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/restaurants': {
      id: '/dashboard/admin/restaurants'
      path: '/admin/restaurants'
      fullPath: '/dashboard/admin/restaurants'
      preLoaderRoute: typeof DashboardAdminRestaurantsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/offers': {
      id: '/dashboard/admin/offers'
      path: '/admin/offers'
      fullPath: '/dashboard/admin/offers'
      preLoaderRoute: typeof DashboardAdminOffersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/offers/edit/$id': {
      id: '/dashboard/offers/edit/$id'
      path: '/offers/edit/$id'
      fullPath: '/dashboard/offers/edit/$id'
      preLoaderRoute: typeof DashboardOffersEditIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminOffersRoute: typeof DashboardAdminOffersRoute
  DashboardAdminRestaurantsRoute: typeof DashboardAdminRestaurantsRoute
  DashboardOffersNewRoute: typeof DashboardOffersNewRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardOffersIndexRoute: typeof DashboardOffersIndexRoute
  DashboardOffersEditIdRoute: typeof DashboardOffersEditIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminOffersRoute: DashboardAdminOffersRoute,
  DashboardAdminRestaurantsRoute: DashboardAdminRestaurantsRoute,
  DashboardOffersNewRoute: DashboardOffersNewRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardOffersIndexRoute: DashboardOffersIndexRoute,
  DashboardOffersEditIdRoute: DashboardOffersEditIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DeleteAccountRoute: DeleteAccountRoute,
  ExploreRoute: ExploreRoute,
  FavoritesRoute: FavoritesRoute,
  OffersRoute: OffersRoute,
  OrdersRoute: OrdersRoute,
  PortalRoute: PortalRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RestaurantsRoute: RestaurantsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  OfferIdRoute: OfferIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
